version: "3"
services:
  auth:
    build:
      context: ../
      dockerfile: Dockerfile_Dev
    env_file:
      - ./env/test.env
    environment:
      - NODE_ENV=development
    network_mode: "host"
    container_name: test
